### ISSUE TITLE
'ptsize' is not respected when '--find_fonts' and '--render_per_font' are used

### ISSUE THREAD

**Issue by Shreeshrii** [amitdo/text2tif#6]
It is possible that this is by design and that the find_fonts feature is just to be used as a sample of what the different text faces look like.

**Comment by Shreeshrii** [comment]
```
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --font Kokila  --outputbase san.Kokila.exp0 --ptsize=32

Rendered page 0 to file san.Kokila.exp0.tif
Rendered page 1 to file san.Kokila.exp0.tif
Rendered page 2 to file san.Kokila.exp0.tif
Rendered page 3 to file san.Kokila.exp0.tif
Rendered page 4 to file san.Kokila.exp0.tif
```

creates the image at text of 32pt. 

![san kokila exp-1](https://cloud.githubusercontent.com/assets/5095331/14038281/85f02750-f274-11e5-8dcb-3b801662bccd.png)

But when --find_fonts and --render_per_font is used --ptsize=32 does not have any effect and only one page is output at default size of 12 pt.

```
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text  --outputbase san.exp-1 --ptsize=32 --strip_unrenderable_words --fontconfig_refresh_config_file=false --leading=32 --char_spacing=0.0 --exposure=-1 --find_fonts --min_coverage=.9 --degrade_image=1 --underline_start_prob=.05 --underline_continuation_prob=.01 


Font AR JULIAN Medium failed with 12996 hits = 16.92%
Aksharyogini2 : 76815 hits = 100.00%, raw = 118 = 99.16%
Rendered page 0 to file san.exp-1.Aksharyogini2.tif
Aksharyogini2 Bold : 76815 hits = 100.00%, raw = 118 = 99.16%
Rendered page 1 to file san.exp-1.Aksharyogini2_Bold.tif
Aparajita : 76816 hits = 100.00%, raw = 119 = 100.00%
Rendered page 2 to file san.exp-1.Aparajita.tif
Aparajita Bold : 76816 hits = 100.00%, raw = 119 = 100.00%
Rendered page 3 to file san.exp-1.Aparajita_Bold.tif
Aparajita Bold Italic : 76816 hits = 100.00%, raw = 119 = 100.00%
Rendered page 4 to file san.exp-1.Aparajita_Bold_Italic.tif
Aparajita Italic : 76816 hits = 100.00%, raw = 119 = 100.00%
Rendered page 5 to file san.exp-1.Aparajita_Italic.tif
Font Arial failed with 12997 hits = 16.92%
Font Arial Bold failed with 12997 hits = 16.92%
```

Sample Output with find fonts is attached after converting to png.
Please note the first line in English (mingw64 is giving error regarding this line, I think)

![san exp-1 aksharyogini2_bold](https://cloud.githubusercontent.com/assets/5095331/14038088/ec7221d4-f271-11e5-924c-62ec9f5f5e79.png)
![san exp-1 aksharyogini2](https://cloud.githubusercontent.com/assets/5095331/14038090/ec7550b6-f271-11e5-8c99-9c0125febe85.png)
![eng arial exp0](https://cloud.githubusercontent.com/assets/5095331/14038089/ec734c80-f271-11e5-86ea-d0b20432fcfd.png)
![ara arial exp0](https://cloud.githubusercontent.com/assets/5095331/14038087/ec7216b2-f271-11e5-824d-581ee2dd4e6a.png)

```
```

**Comment by amitdo** [comment]
> It is possible that this is by design and that the find_fonts feature is just to be used as a sample of what the different text faces look like.

Yes, I believe it's by design.

```
./text2tif --text=../langdata/eng/eng.training.txt --outputbase=../langdata/gen/eng --fonts_dir=/usr/share/fonts --find_fonts --min_coverage=1.0
ls ../langdata/gen | sed 's/eng.//' | sed 's/.tif//'

```

Or, even better:

```
./text2tif --text=../langdata/eng/eng.training.txt --outputbase=../langdata/gen/eng --fonts_dir=/usr/share/fonts --find_fonts --min_coverage=1.0 --render_per_font=false
```

This will produce 'eng.fontlist.txt' file.

I added the second command form to [TrainingTesseract](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#automated-method-new-in-303) wiki page.

**Comment by Shreeshrii** [comment]
This will be very useful. Thanks!

ShreeDevi

---

भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
